param($installationTracker, [string[]] $Suppress = @(), [string[]] $Enable = @(), [hashtable] $Config = @{})

$stage = $installationTracker.StartStage('agentConfig')

# prefs/CLAUDE.md @-includes AGENTS_prat.md.
# Copy it from prat/AGENTS.md. (This copy is .gitignored)
# (We do this instead of "@../prat/AGENTS.md" because even if CC support for that is added, it may be blocked later
# due to security concerns.)
$genHeader = "<!-- Auto-generated by Prat deployment. Edit the source file, not this copy. -->`n`n"
Install-TextToFile $stage "$home\prefs\AGENTS_prat.md" ($genHeader + (Import-TextFile "$home\prat\AGENTS.md"))

Install-Folder $stage "$home\.claude"

if ('installHomeClaudeMd' -notin $Suppress) {
    # Standalone mode (no de): assemble $home/.claude/CLAUDE.md from prat base + prefs fragment.
    # When de is running, it suppresses this and assembles with both prefs and de fragments.
    Install-ClaudeUserConfig $stage "$home\prefs\lib\agents\agent-user_prefs.md"
}

# Global skills from prat, prefs, and (when present) de.
$skillSources = @(
    @{ set = @("testing", "working-with-git", "remember", "plan-format", "start-plan", "pratified-dev-loop", "run-tests", "check-prat-layers",
               "land-step", "reflect", "review-changes", "wrap", "reviewer", "simplify"); srcDir = "$home\prat\lib\agents\skills" }
    @{ set = @("kql-techniques", "wrap-pl", "end-plan"); srcDir = "$home\prefs\lib\agents\skills" }
)
if ($Config.deSkillSources) {
    $skillSources += $Config.deSkillSources
}
Install-ClaudeSkillSet $stage $skillSources "$home/.claude/skills"
Install-ClaudeMarkdownFiles $stage "$home\prat\lib\agents\subagents" "$home/.claude/agents" -Cleanup
Install-ClaudeMarkdownFiles $stage "$home\prat\lib\agents\commands" "$home/.claude/commands" -Cleanup
Install-ClaudeMarkdownFiles $stage "$home\prefs\lib\agents\commands" "$home/.claude/commands" -Cleanup

Install-ClaudeUserSettings $stage

if ('installClaudeSyncFolders' -in $Enable -and $Config.syncFoldersPath) {
    Install-ClaudeSyncFolders $stage $Config.syncFoldersPath
}

if ('installClaudeProjectMemory' -in $Enable) {
    Install-ClaudeProjectMemory $stage
}

if ($Config.deRepoRoot) {
    Install-TextToFile $stage "$($Config.deRepoRoot)\AGENTS_prefs.md" ($genHeader + (Import-TextFile "$home\prefs\AGENTS.md"))
    Install-TextToFile $stage "$($Config.deRepoRoot)\AGENTS_prat.md"  ($genHeader + (Import-TextFile "$home\prat\AGENTS.md"))
}

$installationTracker.EndStage($stage)
