param($installationTracker, [string[]] $Suppress = @(), [string[]] $Enable = @(), [hashtable] $Config = @{})

$stage = $installationTracker.StartStage('agentConfig')

# prefs/CLAUDE.md @-includes AGENTS_prat.md.
# Copy it from prat/AGENTS.md. (This copy is .gitignored)
# (We do this instead of "@../prat/AGENTS.md" because even if CC support for that is added, it may be blocked later
# due to security concerns.)
$genHeader = "<!-- Auto-generated by Prat deployment. Edit the source file, not this copy. -->`n`n"
Install-TextToFile $stage "$home\prefs\AGENTS_prat.md" ($genHeader + (Import-TextFile "$home\prat\AGENTS.md"))

Install-HarnessIntegration $stage 'claude' -Suppress $Suppress -Enable $Enable -Config $Config
Install-HarnessIntegration $stage 'copilot'

if ($Config.deRepoRoot) {
    Install-TextToFile $stage "$($Config.deRepoRoot)\AGENTS_prefs.md" ($genHeader + (Import-TextFile "$home\prefs\AGENTS.md"))
    Install-TextToFile $stage "$($Config.deRepoRoot)\AGENTS_prat.md"  ($genHeader + (Import-TextFile "$home\prat\AGENTS.md"))
}

$installationTracker.EndStage($stage)
